# Global options
project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - posts/spaces.qmd
    - posts/notation_dist.qmd
    - posts/transformers.qmd
    - posts/stochastic-nodes.qmd
    - posts/information.qmd
    - posts/R.qmd

website:
  title: "notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rhngla
format:
  html:
    theme: cosmo
    css: styles.css

editor:
    render-on-save: true