---
title: "Notation for random variables, distributions etc."
author: Rohan Gala
date: "2023-04-27"
date-modified: last-modified
categories: ["math"]
toc: true
number-sections: true
number-depth: 2
highlight-style: github
bibliography: ../refs.bib
format:
  html:
    code-fold: true
    html-math-method: katex

editor:
    render-on-save: true
---

### Distribution

For a continuous random variable $X$, _distribution_ typically refers to the probability density function (pdf) $p_X$. The pdf value at a particular value ox for random variable $X$ is denoted as $p_X(x)$. However it is also common to see $p_X(x)$ being referred to as the distribution.

 | Notation |     Same as        |
 |:--------:|:------------------:|
 | $p(x)$   | $p_{X}(X=x)$       |
 | $p(x|z)$ | $p_{X|Z}(X=x|Z=z)$ |
 | $p(x,z)$ | $p_{X,Z}(X=x,Z=z)$ |

### Parameters or random variables

A distribution with parameters $\theta$ can be denoted as $p_\theta(x)$. In particular, the following notation is interchangeably used in literature:
$$p_\theta(x) \equiv p(x;\theta) \equiv p(x|\theta)$$

Any subtlety in terms of whether the notation choice depends on whether $\theta$ is a parameter (i.e. a constant without a prior distribution associated with it), or is a random variable is up to the author to clarify and use consistently. See community discussions @faisse2014notation, @learner2011notation, and @bartlett2015paramrv.

At times, authors also drop the dependence on $\theta$ and simply write $p_{\theta}(x)$ as $p(x)$. This can be a source of a lot of confusion, and both authors and readers should be careful to prevent misundertanding.

### References

::: {#refs}
:::